
#--------------------------------------------------------------------------------------------
# paths
#--------------------------------------------------------------------------------------------

data_dir: '/datasets/odometry/'
pose_dir: '/datasets/odometry/data_odometry_poses/dataset/poses/'
image_dir: '/datasets/odometry/data_odometry_color/dataset/sequences/'

train_video: ['00', '02', '08', '09']
valid_video: ['03', '04', '05', '06', '07', '10']

seq_len: 2

img_means: [0.19007764876619865, 0.15170388157131237, 0.10659445665650864]
img_stds: [0.2610784009469139, 0.25729316928935814, 0.25163823815039915]

batch_size: 8
